[exynos9810] xfrm/ppp: Fix build regression due to netdev destructor fix.
b0c9e3a4783f (HEAD -> master) net: Fix inconsistent teardown and release of private netdev state.

error: 'struct net_device' has no member named 'destructor'

Signed-off-by: krazey <admin@krazey.de>